// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ejercicio.tareas.domain;

import com.ejercicio.tareas.domain.Tareas;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tareas_Roo_Configurable {
    
    declare @type: Tareas: @Configurable;
    
}
