// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ejercicio.tareas.jsf;

import com.ejercicio.tareas.jsf.MateriasBean;
import java.io.Serializable;

privileged aspect MateriasBean_Roo_Serializable {
    
    declare parents: MateriasBean implements Serializable;
    
    private static final long MateriasBean.serialVersionUID = 1L;
    
}
