// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ejercicio.tareas.jsf;

import com.ejercicio.tareas.jsf.MateriasBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MateriasBean_Roo_Configurable {
    
    declare @type: MateriasBean: @Configurable;
    
}
