// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ejercicio.tareas.jsf;

import com.ejercicio.tareas.jsf.TareasBean;
import java.io.Serializable;

privileged aspect TareasBean_Roo_Serializable {
    
    declare parents: TareasBean implements Serializable;
    
    private static final long TareasBean.serialVersionUID = 1L;
    
}
