// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sergio.roo.jsf.jsf;

import com.sergio.roo.jsf.jsf.DonanteBean;
import java.io.Serializable;

privileged aspect DonanteBean_Roo_Serializable {
    
    declare parents: DonanteBean implements Serializable;
    
    private static final long DonanteBean.serialVersionUID = 1L;
    
}
