// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sergio.roo.jsf.jsf;

import com.sergio.roo.jsf.jsf.OrganoBean;
import java.io.Serializable;

privileged aspect OrganoBean_Roo_Serializable {
    
    declare parents: OrganoBean implements Serializable;
    
    private static final long OrganoBean.serialVersionUID = 1L;
    
}
