// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sergio.roo.jsf.jsf;

import com.sergio.roo.jsf.jsf.OrganoBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OrganoBean_Roo_Configurable {
    
    declare @type: OrganoBean: @Configurable;
    
}
