// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ejercicio.tareas.jsf.converter;

import com.ejercicio.tareas.jsf.converter.MateriasConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MateriasConverter_Roo_Configurable {
    
    declare @type: MateriasConverter: @Configurable;
    
}
